name: Portfolio Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, Linux]

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies and Build
      run: |
        npm install
        npm run build

    - name: Deploy build files to server
      run: |
       # Copy files from build directory
       scp -r ./build/* amku@localhost:/var/www/react/portfolio/
